licenses:
  license: "CC0-1.0"

.travis.yml:
  publisher: "Cache Project"
  license: "CC0-1.0"
  copyright: "2019 Cache Project"
  index: false

.gitignore:
  publisher: "Cache Project"
  license: "CC0-1.0"
  copyright: "2019 Cache Project"
  index: false

run_script.sh:
  publisher: "Cache Project"
  license: "CC0-1.0"
  copyright: "2019 Cache Project"
  index: false

404.md:
  publisher: "Cache Project"
  license: "CC0-1.0"
  copyright: "2019 Cache Project"
  language: "en-US"
  transform: "markdown"
  title: "404 page"
  index: false

source.tar.gz:
  publisher: "Cache Project"
  copyright: "2019 Cache Project"
  title: "The source repository for FreeCache"
