licenses:
  license: "CC0-1.0"

.travis.yml:
  publisher: "Cache Project"
  license: "CC0-1.0"
  copyright: "2019 Cache Project"

.gitignore:
  publisher: "Cache Project"
  license: "CC0-1.0"
  copyright: "2019 Cache Project"

run_script.sh:
  publisher: "Cache Project"
  license: "CC0-1.0"
  copyright: "2019 Cache Project"
