free.md:
  publisher: "Cache Project"
  license: "CC0-1.0"
  copyright: "2019 Cache Project"
  language: "en-US"

format.md:
  publisher: "Cache Project"
  license: "CC0-1.0"
  copyright: "2019 Cache Project"
  language: "en-US"

validator:
  publisher: "Cache Project"
  license: "CC0-1.0"
  copyright: "2019 Cache Project"
